// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button/src/button.vue')['default']
    ButtonSetup: typeof import('./src/components/button/src/button-setup.vue')['default']
    Checkbox: typeof import('./src/components/checkbox/src/checkbox.vue')['default']
    Input: typeof import('./src/components/input/src/input.vue')['default']
    List: typeof import('./src/components/list/src/list.vue')['default']
    Options: typeof import('./src/components/select/src/options.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/select/src/select.vue')['default']
  }
}

export {}
